In [1]:
import torch

In [2]:
x = torch.rand(2, 3, 4)
x

tensor([[[0.3201, 0.2078, 0.5310, 0.2192],
         [0.3308, 0.9243, 0.9585, 0.3664],
         [0.1098, 0.5106, 0.3480, 0.5518]],

        [[0.2869, 0.9523, 0.4132, 0.5944],
         [0.3474, 0.6431, 0.3430, 0.2853],
         [0.5294, 0.5740, 0.3168, 0.4150]]])

In [3]:
x.stride()

(12, 4, 1)

In [4]:
x.is_contiguous()

True

In [5]:
x = x.view(-1,2)

In [6]:
x.is_contiguous()

True

In [7]:
x = x.reshape(2,4,-1)

In [8]:
x.is_contiguous()

True

In [9]:
x.shape

torch.Size([2, 4, 3])

In [10]:
x.transpose_(0,1)
x.shape

torch.Size([4, 2, 3])

In [11]:
x.is_contiguous()

False

In [17]:
y = torch.rand(2, 3)
z = y.view(3,2)

In [19]:
y

tensor([[0.7376, 0.4864, 0.7165],
        [0.7066, 0.0753, 0.4857]])

In [20]:
z

tensor([[0.7376, 0.4864],
        [0.7165, 0.7066],
        [0.0753, 0.4857]])

In [21]:
z.fill_(2)

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])

In [22]:
z

tensor([[2., 2.],
        [2., 2.],
        [2., 2.]])

In [23]:
y

tensor([[2., 2., 2.],
        [2., 2., 2.]])

In [24]:
y.fill_(3)

tensor([[3., 3., 3.],
        [3., 3., 3.]])

In [26]:
z

tensor([[3., 3.],
        [3., 3.],
        [3., 3.]])

In [30]:
x = torch.rand(3,4)
x

tensor([[0.8005, 0.7084, 0.8524, 0.3865],
        [0.2918, 0.2560, 0.2225, 0.7037],
        [0.3039, 0.7979, 0.1168, 0.4985]])

In [31]:
x.t()

tensor([[0.8005, 0.2918, 0.3039],
        [0.7084, 0.2560, 0.7979],
        [0.8524, 0.2225, 0.1168],
        [0.3865, 0.7037, 0.4985]])

In [32]:
y = x.reshape(12,1)
z = x.t().reshape(12,1)

In [33]:
x.fill_(1)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [35]:
y

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]])

In [36]:
z

tensor([[0.8005],
        [0.2918],
        [0.3039],
        [0.7084],
        [0.2560],
        [0.7979],
        [0.8524],
        [0.2225],
        [0.1168],
        [0.3865],
        [0.7037],
        [0.4985]])

In [38]:
print(x.data_ptr())
print(y.data_ptr())
print(z.data_ptr())

140386520554688
140386520554688
140386640088064


In [12]:
import numpy as np
import cv2